[server]
maxUploadSize = 75

[theme]
primaryColor = "#2F855A"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#EDF2F7"
textColor = "#2D3748"
font = "sans serif"

[browser]
gatherUsageStats = false
